# Reuse only the identical first encoder within one automatic-language invocation.
# Guard the complete pinned input, patch and output before touching native source.
if(NOT DEFINED WHISPER_SOURCE_DIR)
    message(FATAL_ERROR "WHISPER_SOURCE_DIR is required")
endif()
set(WHISPER_CPP "${WHISPER_SOURCE_DIR}/src/whisper.cpp")
set(WHISPER_PATCH "${CMAKE_CURRENT_LIST_DIR}/whisper-encoder-reuse.patch")
file(SHA256 "${WHISPER_PATCH}" WHISPER_PATCH_SHA)
if(NOT WHISPER_PATCH_SHA STREQUAL "855c84be455360ddf3455011edf889590682b53738fb31a5ef9c8bdb42c48fc6")
    message(FATAL_ERROR "Whisper first-encoder reuse patch checksum changed")
endif()
file(SHA256 "${WHISPER_CPP}" WHISPER_SOURCE_SHA)
if(WHISPER_SOURCE_SHA STREQUAL "1d51b0a2a731f4b4b1d89d53f2f88cd04fb20b3488aadbb9845ed07c72a9ac39")
    return()
endif()
if(NOT WHISPER_SOURCE_SHA STREQUAL "73dd239fce2fbb57e97ce422e446a2fa16d123148a5e2c05ec5cf6df9df579ea")
    message(FATAL_ERROR "Whisper source differs from the reviewed cancellable first-encoder input")
endif()
find_package(Git REQUIRED)
execute_process(COMMAND "${GIT_EXECUTABLE}" apply --check --whitespace=error-all "${WHISPER_PATCH}"
    WORKING_DIRECTORY "${WHISPER_SOURCE_DIR}" RESULT_VARIABLE WHISPER_CHECK_RESULT)
if(NOT WHISPER_CHECK_RESULT EQUAL 0)
    message(FATAL_ERROR "Whisper first-encoder reuse patch cannot apply cleanly")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" apply --whitespace=error-all "${WHISPER_PATCH}"
    WORKING_DIRECTORY "${WHISPER_SOURCE_DIR}" RESULT_VARIABLE WHISPER_APPLY_RESULT)
if(NOT WHISPER_APPLY_RESULT EQUAL 0)
    message(FATAL_ERROR "Whisper first-encoder reuse patch failed")
endif()
file(SHA256 "${WHISPER_CPP}" WHISPER_OUTPUT_SHA)
if(NOT WHISPER_OUTPUT_SHA STREQUAL "1d51b0a2a731f4b4b1d89d53f2f88cd04fb20b3488aadbb9845ed07c72a9ac39")
    message(FATAL_ERROR "Whisper first-encoder source differs from the reviewed output")
endif()
