package com.mangalens.core.router

import java.io.ByteArrayOutputStream
import java.net.URI
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction

/** App entry carries a saved identity or editable text, never a tool grant or source URL. */
internal sealed interface MangaLensAppEntry {
    data class Reader(val chapterId: String) : MangaLensAppEntry
    data class Orez(val request: String) : MangaLensAppEntry
    data class RecentVideo(val key: String) : MangaLensAppEntry
    data class Downloads(val id: String) : MangaLensAppEntry
}

internal object MangaLensAppEntryPolicy {
    const val MAX_RAW_LENGTH = 12_288
    fun parse(raw: String?): MangaLensAppEntry? = runCatching {
        require(raw != null && raw.length <= MAX_RAW_LENGTH && raw.isNotEmpty())
        val uri = URI(raw)
        require(uri.scheme == "mangalens" && uri.rawFragment == null && uri.rawUserInfo == null && uri.port == -1)
        require(uri.rawAuthority in setOf("reader", "orez", "recent-video", "downloads") && uri.rawPath in listOf("", "/"))
        val pairs = uri.rawQuery?.let { query ->
            require(query.isNotEmpty())
            query.split('&').map { pair ->
                val at = pair.indexOf('='); require(at > 0)
                decode(pair.substring(0, at)) to decode(pair.substring(at + 1))
            }.also { require(it.size <= 1 && it.map { pair -> pair.first }.distinct().size == it.size) }.toMap()
        }.orEmpty()
        when (uri.rawAuthority) {
            "reader" -> {
                require(pairs.keys == setOf("chapter"))
                val id = pairs.getValue("chapter"); require(id.matches(Regex("[a-f0-9]{32}")))
                MangaLensAppEntry.Reader(id)
            }
            "recent-video" -> {
                require(pairs.keys == setOf("key"))
                val key = pairs.getValue("key"); require(key.matches(Regex("[a-f0-9]{64}")))
                MangaLensAppEntry.RecentVideo(key)
            }
            "downloads" -> {
                require(pairs.keys == setOf("focus"))
                val id = pairs.getValue("focus"); require(id.matches(Regex("[A-Za-z0-9_-]{1,100}")))
                MangaLensAppEntry.Downloads(id)
            }
            "orez" -> {
                require(pairs.keys.all { it == "request" })
                val request = pairs["request"].orEmpty()
                require(request.length <= 1024 && request.none { it.isISOControl() && it != '\n' && it != '\t' })
                MangaLensAppEntry.Orez(request)
            }
            else -> error("Unknown app entry")
        }
    }.getOrNull()

    private fun decode(raw: String): String {
        val bytes = ByteArrayOutputStream(raw.length)
        var index = 0
        while (index < raw.length) {
            when (val char = raw[index]) {
                '%' -> {
                    require(index + 2 < raw.length)
                    val high = raw[index + 1].digitToIntOrNull(16); val low = raw[index + 2].digitToIntOrNull(16)
                    require(high != null && low != null)
                    bytes.write(high * 16 + low); index += 3
                }
                '+' -> { bytes.write(32); index++ }
                else -> {
                    // URIs generated by Android Uri.encode are ASCII; reject alternate ambiguous spellings.
                    require(char.code in 0x21..0x7e)
                    bytes.write(char.code); index++
                }
            }
        }
        return Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes.toByteArray())).toString()
    }
}
